baseurl = "http://devopsmtl.com/"
title = "DevOps Montréal"
theme = "ghostwriter"
copyright = "Test"

[languages]
[languages.en]
languageCode = "en-ca"
languageName = "English"
title = "DevOps Montreal"
weight = 0
headline = "DevOps Montreal"
description = "A community of DevOps enthusiasts in the Montreal area"

[[languages.en.menu.main]]
url    = "/pages/about/"
name   = "About"
weight = 0

[[languages.en.menu.main]]
url    = "http://newsletter.devopsmtl.com/"
name   = "Newsletter"
weight = 10

[[languages.en.menu.main]]
url    = "https://www.eventbrite.ca/e/devopsmtl-december-2015-tickets-19828653035"
name   = "Attend"
weight = 20

[[languages.en.menu.main]]
url    = "/pages/present/"
name   = "Present"
weight = 30

[[languages.en.menu.main]]
url    = "/pages/contact-us/"
name   = "Contact Us"
weight = 40

[[languages.en.menu.main]]
url    = "../fr"
name   = "Français"
weight = 100

[languages.fr]
languageCode = "fr-ca"
languageName = "Français"
title = "DevOps Montréal"
weight = 10
headline = "DevOps Montréal"
description = "Communauté montréalaise autour du mouvement DevOps "

[[languages.fr.menu.main]]
url    = "/pages/about/"
name   = "À Propos"
weight = 0

[[languages.fr.menu.main]]
url    = "http://newsletter.devopsmtl.com/"
name   = "Infolettre"
weight = 10

[[languages.fr.menu.main]]
url    = "https://www.eventbrite.ca/e/devopsmtl-december-2015-tickets-19828653035"
name   = "Participer"
weight = 20

[[languages.fr.menu.main]]
url    = "/pages/present/"
name   = "Présenter"
weight = 30

[[languages.fr.menu.main]]
url    = "/pages/contact-us/"
name   = "Nous contacter"
weight = 40

[[languages.fr.menu.main]]
url    = "../"
name   = "English"
weight = 100

[Params]
intro = true
github = "https://github.com/devopsmtl"
twitter = "https://twitter.com/devopsmontreal"
opengraph = true
